export const Events = {
  SIGNUP_STARTED: 'signup_started',
  SIGNUP_COMPLETED: 'signup_completed',
  DEBT_ADDED: 'debt_added',
  INCOME_SAVED: 'income_saved',
  PLAN_GENERATED: 'plan_generated',
  RETURN_SESSION: 'return_session',
  CALCULATOR_CTA_CLICKED: 'calculator_cta_clicked',
  CALCULATOR_STARTED: 'calculator_started',
  CALCULATOR_USED: 'calculator_used',
  CALCULATOR_RESULT_VIEWED: 'calculator_result_viewed',
  CALCULATOR_SAVE_CLICKED: 'calculator_save_clicked',
  PRICING_PRO_CLICKED: 'pricing_pro_clicked',
  UPGRADE_MODAL_VIEWED: 'upgrade_modal_viewed',
  SAVE_PLAN_MODAL_VIEWED: 'save_plan_modal_viewed',
  ONBOARDING_EXPRESS_VIEWED: 'onboarding_express_viewed',
  ONBOARDING_EXPRESS_COMPLETED: 'onboarding_express_completed',
  CHECKOUT_STARTED: 'checkout_started',
  CHECKOUT_SESSION_CREATED: 'checkout_session_created',
  SUBSCRIPTION_STARTED: 'subscription_started',
  PLAN_SAVED_EMAIL: 'plan_saved_email_captured',
  SHARE_CARD_OPENED: 'share_card_opened',
  SHARE_CARD_DOWNLOADED: 'share_card_downloaded',
  REFERRAL_LINK_COPIED: 'referral_link_copied',
  CELEBRATION_FIRED: 'celebration_fired',
  CELEBRATION_FALLBACK: 'celebration_fallback',
  CELEBRATION_RATE_LIMITED: 'celebration_rate_limited',
  ROLL_FORWARD_ADVICE_VIEWED: 'roll_forward_advice_viewed',
  ROLL_FORWARD_ADVICE_REVIEW_CLICKED: 'roll_forward_advice_review_clicked',
  ROLL_FORWARD_ADVICE_PLANNED: 'roll_forward_advice_planned',
  ROLL_FORWARD_ADVICE_DISMISSED: 'roll_forward_advice_dismissed',
} as const;

export type AnalyticsEvent = (typeof Events)[keyof typeof Events];
