/**
 * GET /api/unsubscribe?token=<signed-token>
 *
 * One-click unsubscribe from weekly digest emails.
 * Token is a TTL-bearing HMAC (30-day expiry) generated by
 * generateDigestUnsubscribeToken(). Stateless, no login required.
 *
 * On success: sets user.emailDigest = false, redirects to
 *   /dashboard?tab=settings&unsubscribed=1
 *
 * On expired token: redirects to
 *   /dashboard?tab=settings&expired=1
 *
 * On invalid token: 400 HTML page.
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { verifyDigestUnsubscribeToken } from '@/lib/unsubscribeToken';

const DASHBOARD = 'https://getsnowballpay.com/dashboard';

function escHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;');
}

const htmlPage = (title: string, body: string, accent: string) => `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escHtml(title)} — SnowballPay</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Inter, system-ui, sans-serif; background: #f8fafc; display: flex; align-items: center; justify-content: center; min-height: 100vh; padding: 24px; }
    .card { background: #fff; border-radius: 16px; border: 1px solid rgba(15,23,42,0.08); max-width: 480px; width: 100%; padding: 48px 40px; text-align: center; box-shadow: 0 4px 24px rgba(15,23,42,0.06); }
    .icon { font-size: 48px; margin-bottom: 20px; }
    h1 { font-size: 22px; font-weight: 800; color: #0f172a; margin-bottom: 12px; letter-spacing: -0.02em; }
    p { font-size: 15px; color: #475569; line-height: 1.7; margin-bottom: 28px; }
    a { display: inline-block; background: ${accent}; color: #fff; text-decoration: none; padding: 12px 24px; border-radius: 10px; font-size: 14px; font-weight: 700; }
  </style>
</head>
<body>
  <div class="card">
    ${body}
    <a href="${escHtml(DASHBOARD)}?tab=settings">Manage preferences</a>
  </div>
</body>
</html>`;

export async function GET(request: NextRequest) {
  const token = request.nextUrl.searchParams.get('token') ?? '';

  const result = verifyDigestUnsubscribeToken(token);

  if (!result.ok) {
    if (result.reason === 'expired') {
      return NextResponse.redirect(
        `${DASHBOARD}?tab=settings&expired=1`,
        { status: 302 },
      );
    }
    return new NextResponse(
      htmlPage(
        'Invalid link',
        `<div class="icon">⚠️</div>
         <h1>Invalid unsubscribe link</h1>
         <p>This link is not valid. You can manage your email preferences directly from your dashboard settings.</p>`,
        '#64748b',
      ),
      { status: 400, headers: { 'Content-Type': 'text/html' } },
    );
  }

  try {
    await prisma.user.update({
      where:  { id: result.userId },
      data:   { emailDigest: false },
    });

    return NextResponse.redirect(
      `${DASHBOARD}?tab=settings&unsubscribed=1`,
      { status: 302 },
    );
  } catch {
    return new NextResponse(
      htmlPage(
        'Error',
        `<div class="icon">❌</div>
         <h1>Something went wrong</h1>
         <p>We couldn&apos;t update your preferences. Please try again or manage them from your dashboard settings.</p>`,
        '#ef4444',
      ),
      { status: 500, headers: { 'Content-Type': 'text/html' } },
    );
  }
}
