import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Heading,
  Text,
  Row,
  Column,
} from '@react-email/components';
import * as React from 'react';

interface PayoffItem {
  debtName: string;
  category: string;
  originalBalance: number;
  monthPaidOff: number;
  interestPaid: number;
  orderInPayoff: number;
}

interface PayoffPlanEmailProps {
  userName?: string;
  totalDebt: number;
  totalInterestPaid: number;
  monthlyPayment: number;
  debtFreeDate: string;
  payoffSchedule: PayoffItem[];
  method: string;
}

function fmt(n: number) {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(n);
}

export function PayoffPlanEmail({
  userName,
  totalDebt,
  totalInterestPaid,
  monthlyPayment,
  debtFreeDate,
  payoffSchedule,
  method,
}: PayoffPlanEmailProps) {
  const safeUserName = userName?.replace(/<[^>]*>/g, '').trim();
  const isEmailUserName =
    !!safeUserName &&
    /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(safeUserName);

  const methodLabel =
    method === 'avalanche'
      ? 'Avalanche'
      : method === 'custom'
        ? 'Custom Priority'
        : 'Snowball';

  return (
    <Html>
      <Head />
      <Body
        style={{
          fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
          background: '#f5f7fa',
          margin: 0,
          padding: '40px 0',
        }}
      >
        <Container
          style={{
            maxWidth: '560px',
            margin: '0 auto',
            background: '#ffffff',
            borderRadius: '12px',
            overflow: 'hidden',
            border: '1px solid rgba(15,23,42,0.08)',
          }}
        >
          {/* Header */}
          <Section style={{ background: '#2563eb', padding: '32px 40px' }}>
            <Heading
              style={{
                color: '#ffffff',
                margin: 0,
                fontSize: '22px',
                fontWeight: 700,
              }}
            >
              Your Debt Payoff Plan
            </Heading>
            {safeUserName && (
              <Text
                style={{
                  color: 'rgba(255,255,255,0.8)',
                  margin: '6px 0 0',
                  fontSize: '14px',
                }}
              >
                Hi{' '}
                {isEmailUserName ? (
                  <a
                    href={`mailto:${safeUserName}`}
                    style={{
                      color: '#ffffff',
                      textDecoration: 'none',
                      WebkitTextFillColor: '#ffffff',
                    }}
                  >
                    {safeUserName}
                  </a>
                ) : (
                  <span
                    style={{
                      color: '#ffffff',
                      textDecoration: 'none',
                      WebkitTextFillColor: '#ffffff',
                    }}
                  >
                    {safeUserName}
                  </span>
                )}
                ,
              </Text>
            )}
            <Text
              style={{
                color: 'rgba(255,255,255,0.7)',
                margin: '4px 0 0',
                fontSize: '13px',
              }}
            >
              {methodLabel} method · Generated by SnowballPay
            </Text>
          </Section>

          {/* Summary stats */}
          <Section style={{ padding: '32px 40px 0' }}>
            <Text
              style={{
                fontSize: '11px',
                color: '#94a3b8',
                margin: '0 0 14px',
                textTransform: 'uppercase',
                letterSpacing: '0.06em',
                fontWeight: 600,
              }}
            >
              Plan Summary
            </Text>
            <Row>
              <Column style={{ width: '50%', paddingRight: '6px' }}>
                <div
                  style={{
                    background: '#f8fafc',
                    borderRadius: '8px',
                    padding: '16px',
                    border: '1px solid rgba(15,23,42,0.06)',
                  }}
                >
                  <Text
                    style={{
                      fontSize: '11px',
                      color: '#94a3b8',
                      margin: '0 0 4px',
                    }}
                  >
                    Total Debt
                  </Text>
                  <Text
                    style={{
                      fontSize: '19px',
                      fontWeight: 700,
                      color: '#f87171',
                      margin: 0,
                      fontFamily: 'monospace',
                    }}
                  >
                    {fmt(totalDebt)}
                  </Text>
                </div>
              </Column>
              <Column style={{ width: '50%', paddingLeft: '6px' }}>
                <div
                  style={{
                    background: '#f8fafc',
                    borderRadius: '8px',
                    padding: '16px',
                    border: '1px solid rgba(15,23,42,0.06)',
                  }}
                >
                  <Text
                    style={{
                      fontSize: '11px',
                      color: '#94a3b8',
                      margin: '0 0 4px',
                    }}
                  >
                    Est. Debt-Free
                  </Text>
                  <Text
                    style={{
                      fontSize: '19px',
                      fontWeight: 700,
                      color: '#059669',
                      margin: 0,
                      fontFamily: 'monospace',
                    }}
                  >
                    {debtFreeDate}
                  </Text>
                </div>
              </Column>
            </Row>
            <Row style={{ marginTop: '10px' }}>
              <Column style={{ width: '50%', paddingRight: '6px' }}>
                <div
                  style={{
                    background: '#f8fafc',
                    borderRadius: '8px',
                    padding: '16px',
                    border: '1px solid rgba(15,23,42,0.06)',
                  }}
                >
                  <Text
                    style={{
                      fontSize: '11px',
                      color: '#94a3b8',
                      margin: '0 0 4px',
                    }}
                  >
                    Monthly Payment
                  </Text>
                  <Text
                    style={{
                      fontSize: '19px',
                      fontWeight: 700,
                      color: '#0f172a',
                      margin: 0,
                      fontFamily: 'monospace',
                    }}
                  >
                    {fmt(monthlyPayment)}
                  </Text>
                </div>
              </Column>
              <Column style={{ width: '50%', paddingLeft: '6px' }}>
                <div
                  style={{
                    background: '#f8fafc',
                    borderRadius: '8px',
                    padding: '16px',
                    border: '1px solid rgba(15,23,42,0.06)',
                  }}
                >
                  <Text
                    style={{
                      fontSize: '11px',
                      color: '#94a3b8',
                      margin: '0 0 4px',
                    }}
                  >
                    Total Interest
                  </Text>
                  <Text
                    style={{
                      fontSize: '19px',
                      fontWeight: 700,
                      color: '#2563eb',
                      margin: 0,
                      fontFamily: 'monospace',
                    }}
                  >
                    {fmt(totalInterestPaid)}
                  </Text>
                </div>
              </Column>
            </Row>
          </Section>

          {/* Payoff schedule */}
          <Section style={{ padding: '28px 40px' }}>
            <Text
              style={{
                fontSize: '11px',
                color: '#94a3b8',
                margin: '0 0 14px',
                textTransform: 'uppercase',
                letterSpacing: '0.06em',
                fontWeight: 600,
              }}
            >
              Payoff Order
            </Text>
            {payoffSchedule.map((item, i) => {
              const mo = item.monthPaidOff % 12;
              const yr = Math.floor(item.monthPaidOff / 12);
              const timeStr =
                yr > 0 ? `${yr}y ${mo}m` : `${mo}m`;
              const isLast = i === payoffSchedule.length - 1;
              return (
                <Row
                  key={item.debtName}
                  style={{
                    padding: '12px 0',
                    borderBottom: isLast
                      ? 'none'
                      : '1px solid #f1f5f9',
                  }}
                >
                  <Column style={{ width: '32px', verticalAlign: 'middle' }}>
                    <div
                      style={{
                        width: '24px',
                        height: '24px',
                        borderRadius: '50%',
                        background: '#2563eb',
                        color: '#fff',
                        fontSize: '11px',
                        fontWeight: 700,
                        textAlign: 'center',
                        lineHeight: '24px',
                      }}
                    >
                      {i + 1}
                    </div>
                  </Column>
                  <Column style={{ verticalAlign: 'middle' }}>
                    <Text
                      style={{
                        margin: 0,
                        fontWeight: 600,
                        fontSize: '13px',
                        color: '#0f172a',
                      }}
                    >
                      {item.debtName}
                    </Text>
                    <Text
                      style={{
                        margin: '2px 0 0',
                        fontSize: '12px',
                        color: '#64748b',
                      }}
                    >
                      {fmt(item.originalBalance)} · {item.category} ·{' '}
                      +{fmt(item.interestPaid)} interest
                    </Text>
                  </Column>
                  <Column
                    style={{
                      width: '44px',
                      textAlign: 'right',
                      verticalAlign: 'middle',
                    }}
                  >
                    <Text
                      style={{
                        margin: 0,
                        fontSize: '12px',
                        fontWeight: 600,
                        color: '#475569',
                      }}
                    >
                      {timeStr}
                    </Text>
                  </Column>
                </Row>
              );
            })}
          </Section>

          {/* Footer */}
          <Section
            style={{
              background: '#f8fafc',
              padding: '20px 40px',
              borderTop: '1px solid #f1f5f9',
            }}
          >
            <Text
              style={{
                fontSize: '12px',
                color: '#94a3b8',
                margin: 0,
                textAlign: 'center',
              }}
            >
              Generated by{' '}
              <a
                href="https://getsnowballpay.com"
                style={{ color: '#2563eb', textDecoration: 'none' }}
              >
                SnowballPay
              </a>{' '}
              · You received this because you requested your payoff plan.
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}
